<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| 年セレクトフォーム用配列 
|--------------------------------------------------------------------------
*/

$birth_year         = array();
$passport_from_year = array();
$passport_to_year   = array();

// 現在の年から計算
$year = (int)date('Y');
$birth_year[''] = '選択して下さい';
for ($i = $year; $i >= $year - 100; $i--)
{
    $birth_year[$i] = $i;
}
$passport_from_year[''] = '選択して下さい';
for ($i = $year; $i >= $year - 10; $i--)
{
    $passport_from_year[$i] = $i;
}
$passport_to_year[''] = '選択して下さい';
for ($i = $year; $i <= $year + 10; $i++)
{
    $passport_to_year[$i] = $i;
}

// 設定配列に格納
$config['form_birth_year']         = $birth_year;
$config['form_passport_from_year'] = $passport_from_year;
$config['form_passport_to_year']   = $passport_to_year;

/*
|--------------------------------------------------------------------------
| 月セレクトフォーム用配列 
|--------------------------------------------------------------------------
*/

$month = array(
	'' => '選択して下さい',
	'01' => 'JAN (1)',
	'02' => 'FEB (2)',
	'03' => 'MAR (3)',
	'04' => 'APR (4)',
	'05' => 'MAY (5)',
	'06' => 'JUN (6)',
	'07' => 'JUL (7)',
	'08' => 'AUG (8)',
	'09' => 'SEP (9)',
	'10' => 'OCT (10)',
	'11' => 'NOV (11)',
	'12' => 'DEC (12)',
);
$config['form_month'] = $month;

/*
|--------------------------------------------------------------------------
| 日セレクトフォーム用配列
|--------------------------------------------------------------------------
*/

$day = array();
$day[''] = '選択して下さい';
for ($i = 1; $i <= 31; $i++)
{
    $key = vsprintf('%02d', $i);
    $day[$key] = $i;
}
$config['form_day'] = $day;

/*
|--------------------------------------------------------------------------
| 電話番号種別セレクトフォーム用配列
|--------------------------------------------------------------------------
*/

$config['form_tel_type'] = array(
	'' => '選択してください',
	'home' => '自宅',
	'work' => '勤務先',
	'mobile' => '携帯',
	'other' => 'その他',
);

/*
|--------------------------------------------------------------------------
| 国セレクトフォーム用配列
|--------------------------------------------------------------------------
*/

$all_countrys = array();
$esta_countrys = array();
$all_countrys[''] = '選択して下さい';
$esta_countrys[''] = '選択して下さい';
$lines = file(APPPATH.'config/data/country.tsv');
foreach ($lines as $line)
{
	list($code_s2, $code_s3, $code_i3, $name_jp, $name_eg, $esta) = explode("\t", trim($line));
	$all_countrys[$code_s2] = $name_eg;
	if ($esta === '1')
	{
		$esta_countrys[$code_s2] = $name_eg;
	}
}
$config['form_country_national'] = $esta_countrys;
$config['form_country_birth'] = $all_countrys;
$config['form_country_live'] = $all_countrys;

/*
|--------------------------------------------------------------------------
| 州セレクトフォーム用配列
|--------------------------------------------------------------------------
*/

$config['form_states'] = array(
    '' => '選択してください',
    'XX' => '不明（または未決定です）',
    'AL' => 'ALABAMA',
    'AK' => 'ALASKA',
    'AQ' => 'AMERICAN SAMOA',
    'AZ' => 'ARIZONA',
    'AR' => 'ARKANSAS',
    'CA' => 'CALIFORNIA',
    'EQ' => 'CANTON &amp; ENDERBURY ISL',
    'CO' => 'COLORADO',
    'CT' => 'CONNECTICUT',
    'DE' => 'DELAWARE',
    'DC' => 'DISTRICT OF COLUMBIA',
    'FL' => 'FLORIDA',
    'GA' => 'GEORGIA',
    'GU' => 'GUAM',
    'HI' => 'HAWAII',
    'ID' => 'IDAHO',
    'IL' => 'ILLINOIS',
    'IN' => 'INDIANA',
    'IA' => 'IOWA',
    'KS' => 'KANSAS',
    'KY' => 'KENTUCKY',
    'LA' => 'LOUISIANA',
    'ME' => 'MAINE',
    'MD' => 'MARYLAND',
    'MA' => 'MASSACHUSETTS',
    'MI' => 'MICHIGAN',
    'MN' => 'MINNESOTA',
    'MS' => 'MISSISSIPPI',
    'MO' => 'MISSOURI',
    'MT' => 'MONTANA',
    'NE' => 'NEBRASKA',
    'NV' => 'NEVADA',
    'NH' => 'NEW HAMPSHIRE',
    'NJ' => 'NEW JERSEY',
    'NM' => 'NEW MEXICO',
    'NY' => 'NEW YORK',
    'NC' => 'NORTH CAROLINA',
    'ND' => 'NORTH DAKOTA',
    'CQ' => 'NORTH MARIANA ISL',
    'OH' => 'OHIO',
    'OK' => 'OKLAHOMA',
    'OR' => 'OREGON',
    'PA' => 'PENNSYLVANIA',
    'PR' => 'PUERTO RICO',
    'RI' => 'RHODE ISLAND',
    'SC' => 'SOUTH CAROLINA',
    'SD' => 'SOUTH DAKOTA',
    'TN' => 'TENNESSEE',
    'TX' => 'TEXAS',
    'UT' => 'UTAH',
    'VT' => 'VERMONT',
    'VQ' => 'VIRGIN ISLANDS',
    'VA' => 'VIRGINIA',
    'WA' => 'WASHINGTON',
    'WV' => 'WEST VIRGINIA',
    'WI' => 'WISCONSIN',
    'WY' => 'WYOMING',
);

/*
|--------------------------------------------------------------------------
| その他の国籍レクトフォーム用配列
|--------------------------------------------------------------------------
*/

$config['form_country_other_nation'] = array(
	''   => '選択して下さい',
    'AF' => 'AFGHANISTAN  (AFG)',
    'AX' => 'ALAND ISLANDS  (ALA)',
    'AL' => 'ALBANIA  (ALB)',
    'DZ' => 'ALGERIA  (DZA)',
    'AS' => 'AMERICAN SAMOA  (ASM)',
    'AD' => 'ANDORRA  (AND)',
    'AO' => 'ANGOLA  (AGO)',
    'AI' => 'ANGUILLA  (AIA)',
    'AQ' => 'ANTARCTICA  (ATA)',
    'AG' => 'ANTIGUA AND BARBUDA  (ATG)',
    'AR' => 'ARGENTINA  (ARG)',
    'AM' => 'ARMENIA  (ARM)',
    'AW' => 'ARUBA  (ABW)',
    'AU' => 'AUSTRALIA  (AUS)',
    'AT' => 'AUSTRIA  (AUT)',
    'AZ' => 'AZERBAIJAN  (AZE)',
    'BS' => 'BAHAMAS  (BHS)',
    'BH' => 'BAHRAIN  (BHR)',
    'BD' => 'BANGLADESH  (BGD)',
    'BB' => 'BARBADOS  (BRB)',
    'BY' => 'BELARUS  (BLR)',
    'BE' => 'BELGIUM  (BEL)',
    'BZ' => 'BELIZE  (BLZ)',
    'BJ' => 'BENIN  (BEN)',
    'BM' => 'BERMUDA  (BMU)',
    'BT' => 'BHUTAN  (BTN)',
    'BO' => 'BOLIVIA  (BOL)',
    'BQ' => 'BONAIRE, SINT EUSTATIUS AND SABA  (BES)',
    'BA' => 'BOSNIA AND HERZEGOVINA  (BIH)',
    'BW' => 'BOTSWANA  (BWA)',
    'BV' => 'BOUVET ISLAND  (BVT)',
    'BR' => 'BRAZIL  (BRA)',
    'IO' => 'BRITISH INDIAN OCEAN TERRITORY  (IOT)',
    'BN' => 'BRUNEI  (BRN)',
    'BG' => 'BULGARIA  (BGR)',
    'BF' => 'BURKINA FASO  (BFA)',
    'BU' => 'BURMA  (BUR)',
    'BI' => 'BURUNDI  (BDI)',
    'KH' => 'CAMBODIA  (KHM)',
    'CM' => 'CAMEROON  (CMR)',
    'CA' => 'CANADA  (CAN)',
    'CT' => 'CANTON AND ENDERBURY ISLANDS  (CTE)',
    'CV' => 'CAPE VERDE  (CPV)',
    'KY' => 'CAYMAN ISLANDS  (CYM)',
    'CF' => 'CENTRAL AFRICAN REPUBLIC  (CAF)',
    'TD' => 'CHAD  (TCD)',
    'CL' => 'CHILE  (CHL)',
    'CN' => 'CHINA  (CHN)',
    'CX' => 'CHRISTMAS ISLAND  (CXR)',
    'CC' => 'COCOS (KEELING) ISLANDS  (CCK)',
    'CO' => 'COLOMBIA  (COL)',
    'KM' => 'COMOROS  (COM)',
    'CD' => 'CONGO, DEMOCRATIC REPUBLIC OF  (COD)',
    'CG' => 'CONGO, REPUBLIC OF  (COG)',
    'CK' => 'COOK ISLANDS  (COK)',
    'CR' => 'COSTA RICA  (CRI)',
    'CI' => "COTE D'IVOIRE  (CIV)",
    'HR' => 'CROATIA  (HRV)',
    'CU' => 'CUBA  (CUB)',
    'CW' => 'CURACAO  (CUW)',
    'CY' => 'CYPRUS  (CYP)',
    'CZ' => 'CZECH REPUBLIC  (CZE)',
    'YD' => 'DEMOCRATIC YEMEN  (YMD)',
    'DK' => 'DENMARK  (DNK)',
    'DJ' => 'DJIBOUTI  (DJI)',
    'DM' => 'DOMINICA  (DMA)',
    'DO' => 'DOMINICAN REPUBLIC  (DOM)',
    'NQ' => 'DRONNING MAUD LAND  (DML)',
    'TP' => 'EAST TIMOR  (TMP)',
    'EC' => 'ECUADOR  (ECU)',
    'EG' => 'EGYPT  (EGY)',
    'SV' => 'EL SALVADOR  (SLV)',
    'GQ' => 'EQUATORIAL GUINEA  (GNQ)',
    'ER' => 'ERITREA  (ERI)',
    'EE' => 'ESTONIA  (EST)',
    'ET' => 'ETHIOPIA  (ETH)',
    'FK' => 'FALKLAND ISLANDS  (FLK)',
    'FO' => 'FAROE ISLANDS  (FRO)',
    'FJ' => 'FIJI  (FJI)',
    'FI' => 'FINLAND  (FIN)',
    'FR' => 'FRANCE  (FRA)',
    'FX' => 'FRANCE METROPOLITAN  (FXX)',
    'GF' => 'FRENCH GUIANA  (GUF)',
    'PF' => 'FRENCH POLYNESIA  (PYF)',
    'TF' => 'FRENCH SOUTHERN TERRITORIES  (ATF)',
    'GA' => 'GABON  (GAB)',
    'GM' => 'GAMBIA  (GMB)',
    'GE' => 'GEORGIA  (GEO)',
    'DE' => 'GERMANY  (DEU)',
    'GH' => 'GHANA  (GHA)',
    'GI' => 'GIBRALTAR  (GIB)',
    'GR' => 'GREECE  (GRC)',
    'GL' => 'GREENLAND  (GRL)',
    'GD' => 'GRENADA  (GRD)',
    'GP' => 'GUADELOUPE  (GLP)',
    'GU' => 'GUAM  (GUM)',
    'GT' => 'GUATEMALA  (GTM)',
    'GG' => 'GUERNSEY  (GGY)',
    'GN' => 'GUINEA  (GIN)',
    'GW' => 'GUINEA-BISSAU  (GNB)',
    'GY' => 'GUYANA  (GUY)',
    'HT' => 'HAITI  (HTI)',
    'HM' => 'HEARD AND MC DONALD ISLANDS  (HMD)',
    'HN' => 'HONDURAS  (HND)',
    'HK' => 'HONG KONG  (HKG)',
    'HU' => 'HUNGARY  (HUN)',
    'IS' => 'ICELAND  (ISL)',
    'IN' => 'INDIA  (IND)',
    'ID' => 'INDONESIA  (IDN)',
    'IR' => 'IRAN  (IRN)',
    'IQ' => 'IRAQ  (IRQ)',
    'IE' => 'IRELAND  (IRL)',
    'IM' => 'ISLE OF MAN  (IMN)',
    'IL' => 'ISRAEL  (ISR)',
    'IT' => 'ITALY  (ITA)',
    'JM' => 'JAMAICA  (JAM)',
    'JP' => 'JAPAN  (JPN)',
    'JE' => 'JERSEY  (JEY)',
    'JT' => 'JOHNSTON ISLAND  (JTN)',
    'JO' => 'JORDAN  (JOR)',
    'KZ' => 'KAZAKHSTAN  (KAZ)',
    'KE' => 'KENYA  (KEN)',
    'KI' => 'KIRIBATI  (KIR)',
    'KV' => 'KOSOVO  (KVV)',
    'KW' => 'KUWAIT  (KWT)',
    'KG' => 'KYRGYZSTAN  (KGZ)',
    'LA' => 'LAOS  (LAO)',
    'LV' => 'LATVIA  (LVA)',
    'LB' => 'LEBANON  (LBN)',
    'LS' => 'LESOTHO  (LSO)',
    'LR' => 'LIBERIA  (LBR)',
    'LY' => 'LIBYA  (LBY)',
    'LI' => 'LIECHTENSTEIN  (LIE)',
    'LT' => 'LITHUANIA  (LTU)',
    'LU' => 'LUXEMBOURG  (LUX)',
    'MO' => 'MACAU  (MAC)',
    'MK' => 'MACEDONIA  (MKD)',
    'MG' => 'MADAGASCAR  (MDG)',
    'MW' => 'MALAWI  (MWI)',
    'MY' => 'MALAYSIA  (MYS)',
    'MV' => 'MALDIVES  (MDV)',
    'ML' => 'MALI  (MLI)',
    'MT' => 'MALTA  (MLT)',
    'MH' => 'MARSHALL ISLANDS  (MHL)',
    'MQ' => 'MARTINIQUE  (MTQ)',
    'MR' => 'MAURITANIA  (MRT)',
    'MU' => 'MAURITIUS  (MUS)',
    'YT' => 'MAYOTTE  (MYT)',
    'MX' => 'MEXICO  (MEX)',
    'FM' => 'MICRONESIA - FEDERATED STATES OF  (FSM)',
    'MI' => 'MIDWAY ISLANDS  (MID)',
    'MD' => 'MOLDOVA  (MDA)',
    'MC' => 'MONACO  (MCO)',
    'MN' => 'MONGOLIA  (MNG)',
    'ME' => 'MONTENEGRO  (MNE)',
    'MS' => 'MONTSERRAT  (MSR)',
    'MA' => 'MOROCCO  (MAR)',
    'MZ' => 'MOZAMBIQUE  (MOZ)',
    'MM' => 'MYANMAR  (MMR)',
    'NA' => 'NAMIBIA  (NAM)',
    'NR' => 'NAURU  (NRU)',
    'NP' => 'NEPAL  (NPL)',
    'NL' => 'NETHERLANDS  (NLD)',
    'AN' => 'NETHERLANDS ANTILLES  (ANT)',
    'NT' => 'NEUTRAL ZONE  (NTZ)',
    'NC' => 'NEW CALEDONIA  (NCL)',
    'NZ' => 'NEW ZEALAND  (NZL)',
    'NI' => 'NICARAGUA  (NIC)',
    'NE' => 'NIGER  (NER)',
    'NG' => 'NIGERIA  (NGA)',
    'NU' => 'NIUE  (NIU)',
    'NF' => 'NORFOLK ISLAND  (NFK)',
    'KP' => 'NORTH KOREA  (PRK)',
    'MP' => 'NORTHERN MARIANA ISLANDS  (MNP)',
    'NO' => 'NORWAY  (NOR)',
    'OM' => 'OMAN  (OMN)',
    'PK' => 'PAKISTAN  (PAK)',
    'PW' => 'PALAU  (PLW)',
    'PS' => 'PALESTINIAN TERRITORIES  (PSE)',
    'PA' => 'PANAMA  (PAN)',
    'PG' => 'PAPUA NEW GUINEA  (PNG)',
    'PY' => 'PARAGUAY  (PRY)',
    'PE' => 'PERU  (PER)',
    'PH' => 'PHILIPPINES  (PHL)',
    'PN' => 'PITCAIRN ISLANDS  (PCN)',
    'PL' => 'POLAND  (POL)',
    'PT' => 'PORTUGAL  (PRT)',
    'PR' => 'PUERTO RICO  (PRI)',
    'QA' => 'QATAR  (QAT)',
    'RE' => 'REUNION  (REU)',
    'RO' => 'ROMANIA  (ROM)',
    'RU' => 'RUSSIA  (RUS)',
    'RW' => 'RWANDA  (RWA)',
    'BL' => 'SAINT BARTHELEMY  (BLM)',
    'KN' => 'SAINT KITTS AND NEVIS  (KNA)',
    'LC' => 'SAINT LUCIA  (LCA)',
    'MF' => 'SAINT MARTIN (FRENCH PART)  (MAF)',
    'VC' => 'SAINT VINCENT AND THE GRENADINES  (VCT)',
    'WS' => 'SAMOA  (WSM)',
    'SM' => 'SAN MARINO  (SMR)',
    'ST' => 'SAO TOME AND PRINCIPE  (STP)',
    'SA' => 'SAUDI ARABIA  (SAU)',
    'SN' => 'SENEGAL  (SEN)',
    'RS' => 'SERBIA  (SRB)',
    'CS' => 'SERBIA AND MONTENEGRO  (SCG)',
    'SC' => 'SEYCHELLES  (SYC)',
    'SL' => 'SIERRA LEONE  (SLE)',
    'SG' => 'SINGAPORE  (SGP)',
    'SX' => 'SINT MAARTEN (DUTCH PART)  (SXM)',
    'SK' => 'SLOVAKIA  (SVK)',
    'SI' => 'SLOVENIA  (SVN)',
    'SB' => 'SOLOMON ISLANDS  (SLB)',
    'SO' => 'SOMALIA  (SOM)',
    'ZA' => 'SOUTH AFRICA  (ZAF)',
    'GS' => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS  (SGS)',
    'KR' => 'SOUTH KOREA  (KOR)',
    'SS' => 'SOUTH SUDAN  (SSD)',
    'ES' => 'SPAIN  (ESP)',
    'LK' => 'SRI LANKA  (LKA)',
    'SH' => 'ST. HELENA  (SHN)',
    'PM' => 'ST. PIERRE AND MIQUELON  (SPM)',
    'SD' => 'SUDAN  (SDN)',
    'SR' => 'SURINAME  (SUR)',
    'SJ' => 'SVALBARD AND JAN MAYEN ISLANDS  (SJM)',
    'SZ' => 'SWAZILAND  (SWZ)',
    'SE' => 'SWEDEN  (SWE)',
    'CH' => 'SWITZERLAND  (CHE)',
    'SY' => 'SYRIA  (SYR)',
    'TW' => 'TAIWAN  (TWN)',
    'TJ' => 'TAJIKISTAN  (TJK)',
    'TZ' => 'TANZANIA  (TZA)',
    'TH' => 'THAILAND  (THA)',
    'TL' => 'TIMOR-LESTE  (TLS)',
    'TG' => 'TOGO  (TGO)',
    'TK' => 'TOKELAU  (TKL)',
    'TO' => 'TONGA  (TON)',
    'TT' => 'TRINIDAD AND TOBAGO  (TTO)',
    'TN' => 'TUNISIA  (TUN)',
    'TR' => 'TURKEY  (TUR)',
    'TM' => 'TURKMENISTAN  (TKM)',
    'TC' => 'TURKS AND CAICOS ISLANDS  (TCA)',
    'TV' => 'TUVALU  (TUV)',
    'UG' => 'UGANDA  (UGA)',
    'UA' => 'UKRAINE  (UKR)',
    'AE' => 'UNITED ARAB EMIRATES  (ARE)',
    'GB' => 'UK - BRITISH CITIZEN  (GBR)',
    'US' => 'UNITED STATES  (USA)',
    'UM' => 'UNITED STATES MINOR OUTLYING ISLANDS  (UMI)',
    'UY' => 'URUGUAY  (URY)',
    'UZ' => 'UZBEKISTAN  (UZB)',
    'VU' => 'VANUATU  (VUT)',
    'VA' => 'VATICAN CITY STATE (HOLY SEE)  (VAT)',
    'VE' => 'VENEZUELA  (VEN)',
    'VN' => 'VIETNAM  (VNM)',
    'VG' => 'VIRGIN ISLANDS (BRITISH)  (VGB)',
    'VI' => 'VIRGIN ISLANDS (U.S.)  (VIR)',
    'WK' => 'WAKE ISLAND  (WAK)',
    'WF' => 'WALLIS AND FUTUNA ISLANDS  (WLF)',
    'EH' => 'WESTERN SAHARA  (ESH)',
    'YE' => 'YEMEN  (YEM)',
    'ZR' => 'ZAIRE  (ZAR)',
    'ZM' => 'ZAMBIA  (ZMB)',
    'ZW' => 'ZIMBABWE  (ZWE)',
);

/*
|--------------------------------------------------------------------------
| 国番号用配列
|--------------------------------------------------------------------------
*/

$config['form_country_phone_code'] = array(
    '93' => 'Afghanistan (+93)',
    '355' => 'Albania (+355)',
    '213' => 'Algeria (+213)',
    '1684' => 'American Samoa (+1684)',
    '376' => 'Andorra (+376)',
    '244' => 'Angola (+244)',
    '1264' => 'Anguilla (+1264)',
    '672' => 'Antarctica (+672)',
    '1268' => 'Antigua (+1268)',
    '54' => 'Argentina (+54)',
    '374' => 'Armenia (+374)',
    '297' => 'Aruba (+297)',
    '247' => 'Ascension (+247)',
    '61' => 'Australia (+61)',
    '672' => 'Australian External Territories (+672)',
    '43' => 'Austria (+43)',
    '994' => 'Azerbaijan (+994)',
    '1242' => 'Bahamas (+1242)',
    '973' => 'Bahrain (+973)',
    '880' => 'Bangladesh (+880)',
    '1246' => 'Barbados (+1246)',
    '1268' => 'Barbuda (+1268)',
    '375' => 'Belarus (+375)',
    '32' => 'Belgium (+32)',
    '501' => 'Belize (+501)',
    '229' => 'Benin (+229)',
    '1441' => 'Bermuda (+1441)',
    '975' => 'Bhutan (+975)',
    '591' => 'Bolivia (+591)',
    '387' => 'Bosnia &amp; Herzegovina (+387)',
    '267' => 'Botswana (+267)',
    '55' => 'Brazil (+55)',
    '673' => 'Brunei Darussalam (+673)',
    '359' => 'Bulgaria (+359)',
    '226' => 'Burkina Faso (+226)',
    '257' => 'Burundi (+257)',
    '855' => 'Cambodia (+855)',
    '237' => 'Cameroon (+237)',
    '1' => 'Canada (+1)',
    '238' => 'Cape Verde Islands (+238)',
    '1345' => 'Cayman Islands (+1345)',
    '236' => 'Central African Republic (+236)',
    '235' => 'Chad (+235)',
    '64' => 'Chatham Island (+64)',
    '56' => 'Chile (+56)',
    '86' => 'China (PRC) (+86)',
    '53' => 'Christmas Island (+53)',
    '57' => 'Colombia (+57)',
    '269' => 'Comoros (+269)',
    '242' => 'Congo (+242)',
    '243' => 'Congo, Dem. Rep. of (former Zaire) (+243)',
    '682' => 'Cook Islands (+682)',
    '506' => 'Costa Rica (+506)',
    '225' => "Cote d'Ivoire (+225)",
    '385' => 'Croatia (+385)',
    '53' => 'Cuba (+53)',
    '599' => 'Curacao (+599)',
    '357' => 'Cyprus (+357)',
    '420' => 'Czech Republic (+420)',
    '45' => 'Denmark (+45)',
    '246' => 'Diego Garcia (+246)',
    '253' => 'Djibouti (+253)',
    '1767' => 'Dominica (+1767)',
    '1809' => 'Dominican Republic (+1809)',
    '1829' => 'Dominican Republic (+1829)',
    '670' => 'East Timor (+670)',
    '56' => 'Easter Island (+56)',
    '593' => 'Ecuador (+593)',
    '20' => 'Egypt (+20)',
    '503' => 'El Salvador (+503)',
    '240' => 'Equatorial Guinea (+240)',
    '291' => 'Eritrea (+291)',
    '372' => 'Estonia (+372)',
    '251' => 'Ethiopia (+251)',
    '500' => 'Falkland Islands (Malvinas) (+500)',
    '298' => 'Faroe Islands (+298)',
    '679' => 'Fiji Islands (+679)',
    '358' => 'Finland (+358)',
    '33' => 'France (+33)',
    '596' => 'French Antilles (+596)',
    '594' => 'French Guiana (+594)',
    '689' => 'French Polynesia (+689)',
    '241' => 'Gabonese Republic (+241)',
    '220' => 'Gambia (+220)',
    '995' => 'Georgia (+995)',
    '49' => 'Germany (+49)',
    '233' => 'Ghana (+233)',
    '350' => 'Gibraltar (+350)',
    '30' => 'Greece (+30)',
    '299' => 'Greenland (+299)',
    '1473' => 'Grenada (+1473)',
    '590' => 'Guadeloupe (+590)',
    '1671' => 'Guam (+1671)',
    '502' => 'Guatemala (+502)',
    '224' => 'Guinea (+224)',
    '245' => 'Guinea-Bissau (+245)',
    '592' => 'Guyana (+592)',
    '509' => 'Haiti (+509)',
    '504' => 'Honduras (+504)',
    '852' => 'Hong Kong (+852)',
    '36' => 'Hungary (+36)',
    '354' => 'Iceland (+354)',
    '91' => 'India (+91)',
    '62' => 'Indonesia (+62)',
    '98' => 'Iran (+98)',
    '353' => 'Ireland (+353)',
    '964' => 'Iraq (+964)',
    '972' => 'Israel (+972)',
    '39' => 'Italy (+39)',
    '1876' => 'Jamaica (+1876)',
    '81' => 'Japan (+81)',
    '962' => 'Jordan (+962)',
    '7' => 'Kazakhstan (+7)',
    '254' => 'Kenya (+254)',
    '686' => 'Kiribati (+686)',
    '850' => 'Korea (North) (+850)',
    '82' => 'Korea (South) (+82)',
    '965' => 'Kuwait (+965)',
    '996' => 'Kyrgyz Republic (+996)',
    '856' => 'Laos (+856)',
    '371' => 'Latvia (+371)',
    '961' => 'Lebanon (+961)',
    '266' => 'Lesotho (+266)',
    '231' => 'Liberia (+231)',
    '218' => 'Libya (+218)',
    '423' => 'Liechtenstein (+423)',
    '370' => 'Lithuania (+370)',
    '352' => 'Luxembourg (+352)',
    '853' => 'Macao (+853)',
    '389' => 'Macedonia (Former Yugoslav Rep. of) (+389)',
    '261' => 'Madagascar (+261)',
    '265' => 'Malawi (+265)',
    '60' => 'Malaysia (+60)',
    '960' => 'Maldives (+960)',
    '223' => 'Mali Republic (+223)',
    '356' => 'Malta (+356)',
    '692' => 'Marshall Islands (+692)',
    '596' => 'Martinique (+596)',
    '222' => 'Mauritania (+222)',
    '230' => 'Mauritius (+230)',
    '269' => 'Mayotte Island (+269)',
    '52' => 'Mexico (+52)',
    '691' => 'Micronesia (Federal States of) (+691)',
    '1808' => 'Midway Island (+1808)',
    '373' => 'Moldova (+373)',
    '377' => 'Monaco (+377)',
    '976' => 'Mongolia (+976)',
    '382' => 'Montenegro (+382)',
    '1664' => 'Montserrat (+1664)',
    '212' => 'Morocco (+212)',
    '258' => 'Mozambique (+258)',
    '95' => 'Myanmar (+95)',
    '264' => 'Namibia (+264)',
    '674' => 'Nauru (+674)',
    '977' => 'Nepal (+977)',
    '31' => 'Netherlands (+31)',
    '599' => 'Netherlands Antilles (+599)',
    '1869' => 'Nevis (+1869)',
    '687' => 'New Caledonia (+687)',
    '64' => 'New Zealand (+64)',
    '505' => 'Nicaragua (+505)',
    '227' => 'Niger (+227)',
    '234' => 'Nigeria (+234)',
    '683' => 'Niue (+683)',
    '672' => 'Norfolk Island (+672)',
    '670' => 'Northern Marianas Islands (+670)',
    '47' => 'Norway (+47)',
    '968' => 'Oman (+968)',
    '92' => 'Pakistan (+92)',
    '680' => 'Palau (+680)',
    '680' => 'Palestinian Settlements (+970)',
    '507' => 'Panama (+507)',
    '675' => 'Papua New Guinea (+675)',
    '595' => 'Paraguay (+595)',
    '51' => 'Peru (+51)',
    '63' => 'Philippines (+63)',
    '48' => 'Poland (+48)',
    '351' => 'Portugal (+351)',
    '1787' => 'Puerto Rico (+1787)',
    '1939' => 'Puerto Rico (+1939)',
    '974' => 'Qatar (+974)',
    '262' => 'Reunion (+262)',
    '40' => 'Romania (+40)',
    '7' => 'Russia (+7)',
    '250' => 'Rwandese Republic (+250)',
    '685' => 'Samoa (+685)',
    '378' => 'San Marino (+378)',
    '239' => 'Sao Tome &amp; Principe (+239)',
    '966' => 'Saudi Arabia (+966)',
    '221' => 'Senegal (+221)',
    '381' => 'Serbia (+381)',
    '248' => 'Seychelles Republic (+248)',
    '232' => 'Sierra Leone (+232)',
    '65' => 'Singapore (+65)',
    '421' => 'Slovak Republic (+421)',
    '386' => 'Slovenia (+386)',
    '677' => 'Solomon Islands (+677)',
    '252' => 'Somali Democratic Republic (+252)',
    '27' => 'South Africa (+27)',
    '34' => 'Spain (+34)',
    '94' => 'Sri Lanka (+94)',
    '290' => 'St. Helena (+290)',
    '1869' => 'St. Kitts (+1869)',
    '1758' => 'St. Lucia (+1758)',
    '508' => 'St. Pierre &amp; Miquelon (+508)',
    '784' => 'St. Vincent &amp; Grenadines (+784)',
    '249' => 'Sudan (+249)',
    '597' => 'Suriname (+597)',
    '268' => 'Swaziland (+268)',
    '46' => 'Sweden (+46)',
    '41' => 'Switzerland (+41)',
    '963' => 'Syria (+963)',
    '886' => 'Taiwan (+886)',
    '992' => 'Tajikistan (+992)',
    '255' => 'Tanzania (+255)',
    '66' => 'Thailand (+66)',
    '228' => 'Togolese Republic (+228)',
    '690' => 'Tokelau (+690)',
    '676' => 'Tonga Islands (+676)',
    '1868' => 'Trinidad &amp; Tobago (+1868)',
    '216' => 'Tunisia (+216)',
    '90' => 'Turkey (+90)',
    '993' => 'Turkmenistan (+993)',
    '1649' => 'Turks &amp; Caicos Islands (+1649)',
    '688' => 'Tuvalu (+688)',
    '256' => 'Uganda (+256)',
    '380' => 'Ukraine (+380)',
    '971' => 'United Arab Emirates (+971)',
    '44' => 'United Kingdom (+44)',
    '1' => 'United States of America (+1)',
    '598' => 'Uruguay (+598)',
    '998' => 'Uzbekistan (+998)',
    '678' => 'Vanuatu (+678)',
    '379' => 'Vatican City (+379)',
    '58' => 'Venezuela (+58)',
    '84' => 'Vietnam (+84)',
    '1284' => 'Virgin Islands - British (+1284)',
    '1340' => 'Virgin Islands - US (+1340)',
    '808' => 'Wake Island (+808)',
    '681' => 'Wallis &amp; Futuna (+681)',
    '969' => 'Yemen (North) (+969)',
    '967' => 'Yemen (South) (+967)',
    '381' => 'Yugoslavia (+381)',
    '260' => 'Zambia (+260)',
    '255' => 'Zanzibar (+255)',
    '263' => 'Zimbabwe (+263)',
);
